language: node_js
env:
  global:
    - ENCRYPTION_LABEL: 9642c89db52e
    - GIT_DEPLOY_USERNAME: TravisCI
    - GIT_DEPLOY_EMAIL: draff8660+travisci@gmail.com
    - GH_PAGES_CNAME: wizweek.com
cache:
  directories:
    - node_modules
    - bower_components
before_script:
  - npm install -g bower
  - bower install
script:
  - bin/travis_build_and_deploy.sh
